version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@pgbouncer:6432/db # remove ?schema=public for pgbouncer 
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=pgbouncer
      - DATABASE_PORT=6432
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_DB=db
      - DATABASE_SCHEMA=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=password
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - pgbouncer
      - redis

  db:
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    expose:
      - 5432

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    command: ["pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
